name: 'hk_bnt_vaccine_booking_check'

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * *'

# jobs: many jobs construct a whole Action
jobs:
  check-booking-slot:
    runs-on: ubuntu-latest
    # declare the detail of jobs
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2 # setup python runtime env
        with: 
          python-version: 3.6 #install the python needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run python script
        run: |
            python ./github/workflows/for_github_action.py
      - name: '[Git] add json file'
        run: git add .
      - name: '[Git] commit json = files'
        run: git commit -m "update json"
      - name: '[Git] fetch from master'
        run: git fetch origin master
      - name: '[Git] push code'
        run: git push origin HEAD:master

