# This is a basic workflow to help you get started with Actions

name: 'hk_bnt_vaccine_booking_check'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2 # setup python runtime env
        with: 
          python-version: 3.6 #install the python needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run python script
        run: |
            python ./github/workflows/for_github_action.py
      - name: '[Git] add json file'
        run: git add .
      - name: '[Git] commit json = files'
        run: git commit -m "update json"
      - name: '[Git] fetch from master'
        run: git fetch origin main
      - name: '[Git] push code'
        run: git push origin HEAD:main
